name: User Story
description: A feature or requirement expressed from the user's perspective.
title: "feat: "
labels: ["enhancement"]
body:
  - type: textarea
    id: story
    attributes:
      label: User Story
      description: "Format: As a <role>, I want <feature>, so that <benefit>."
      placeholder: |
        As a ...
        I want ...
        So that ...
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: "List the specific conditions that must be met for this story to be considered done."
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: textarea
    id: technical_notes
    attributes:
      label: Technical Notes / Approach
      description: "Any technical constraints, architectural decisions, or implementation details (consult CTO if needed)."
      placeholder: |
        - Use the `project-management` skill.
        - Ensure Lofi Gate is passing.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### Definition of Done
        - [ ] Tests passed (Red-Green-Refactor)
        - [ ] Code reviewed
        - [ ] Documentation updated
