name: Bug Report
description: Create a report to help us improve.
title: "fix: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "A clear and concise description of what the bug is."
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction Steps
      description: "How do we make it happen?"
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: "What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: "What actually happened?"
    validations:
      required: true
